[project]
name = "rl-fundamental-trading"
version = "0.1.0"
description = "RL fundamental trading project"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "rl-ss26-market-data-pipeline",
]

[tool.uv]
package = false

[tool.uv.sources]
rl-ss26-market-data-pipeline = { git = "https://gitlab.lrz.de/daniel.maier/rl-ss26-market-data-pipeline.git", rev = "cee324de7b80e1e6e0c5531d1a19db0c6ca0f13d" }
